# Generated by Django 5.2 on 2025-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='club',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название клуба'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_toastmasters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='visit_form',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=50, verbose_name='Формат посещения'),
        ),
    ]
